plugins:
- jekyll-remote-theme
- jekyll-redirect-from


title: Power Monitor for Raspberry Pi
description: All inclusive hardware and software project for complete home energy monitoring.
remote_theme: just-the-docs/just-the-docs

url: https://david00.github.io
baseurl: "/rpi-power-monitor"

# Search Settings
search_enabled: true
search.heading_level: 1

# Copy button
enable_copy_code_button: true

# Latest version for the documentation
latest-version: v0.3.0

# Latest version for the custom OS image (needs to be updated to support the 'v' in the version name of the image). The v0.2.0 image path is:
# https://github.com/David00/rpi-power-monitor/releases/download/v0.2.0/Raspberry-Pi-OS-Lite_rpi_power_monitor-0.2.0+release.zip
# So the path contains the 'v', but the filename does not.

latest-os-image: v0.3.0

collections:
  docs:
    output: true

color_scheme: powermon_light

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    docs:
      output: true
  
callouts:
  info:
    title: Info
    color: blue
  example-cream:
    title: Example
    color: palette-cream
  note-cream:
    title: Note
    color: palette-cream
  reference-cream:
    title: Reference
    color: palette-cream
  note-aqua:
    title: Note
    color: palette-aqua
  pro-aqua:
    title: Pro Tip
    color: palette-aqua
  note-yellow:
    title: Note
    color: palette-yellow
  note-blue:
    title: Note
    color: palette-blue
  note-dark-blue:
    title: Note
    color: palette-dark-blue
  note-red:
    title: Note
    color: palette-red
  warning:
    title: Warning
    color: palette-red
  danger:
    title: Danger!
    color: palette-red