{
 "title": "Home Power Dashboard",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cost_per_kWh", "query": "0.12" }
  ]
 },
 "panels": [
  {
   "title": "Solar Production",
   "type": "singlestat",
   "description": "This is the total amount of energy your solar panels have produced.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    {
     "measurement": "solar",
     "query": "SELECT integral(\"power\") FROM \"solar\" WHERE (\"time\" > '2020-04-07') AND $timeFilter GROUP BY time(8h)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Home Consumption",
   "type": "singlestat",
   "description": "This is the total amount of energy your home has used.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    {
     "measurement": "home_load",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net Energy",
   "type": "singlestat",
   "description": "For grid-tied solar system users only:\nThis is the amount of power you have either imported from or exported to the grid. Negative values means you overproduced. Positive values means you payed for power.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "net",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Overall Status",
   "type": "singlestat",
   "description": "For grid-tied solar panel system users only:\n- Consuming means you are currently importing power from the grid\n- Producing means you are currently sending power back into the grid.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$tag_status",
     "groupBy": [
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT \"power\" FROM \"net\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Peak Production",
   "type": "singlestat",
   "description": "The high instantaneous production value measured by your solar PV CT.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "watt",
   "valueName": "max",
   "targets": [
    {
     "measurement": "solar",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Peak Consumption",
   "type": "singlestat",
   "description": "The maximum measured consumption from \"Home Power Consumption\"",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "watt",
   "valueName": "max",
   "targets": [
    {
     "measurement": "home_load",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Cost",
   "type": "stat",
   "description": "This is an approximate cost based on a fixed rate/kWh. Set your rate in Dashboard Settings -> Variables",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nSELECT integral(\"power\") * [[cost_per_kWh]]/3600000 FROM \"net\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Home Power Usage",
   "type": "graph",
   "description": "This panel shows the current power being used at home. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "alias": "Home Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "home_load",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Power",
   "type": "graph",
   "description": "By default, this chart will show zero, because you have to set up solar integration in the code manually. See the Wiki section titled \"Solar PV Integration\"",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "alias": "PV Production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "solar",
     "query": "SELECT mean(\"power\") FROM \"solar\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net Utilization",
   "type": "graph",
   "description": "This panel shows net power consumption. \n\nPositive values are net consumption. \n\nNegative values are net production.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "alias": "Net Power Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Amperage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "PV Amperage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "solar",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Home Amperage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "home_load",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}