{
 "title": "Home Power Dashboard",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Solar Production",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    {
     "measurement": "solar",
     "query": "SELECT integral(\"power\") FROM \"solar\" WHERE (\"time\" > '2020-04-07') AND $timeFilter GROUP BY time(8h)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Home Consumption",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    {
     "measurement": "home_load",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net Energy",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "net",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Overall Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$tag_status",
     "groupBy": [
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT \"power\" FROM \"net\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Peak Production",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "watt",
   "valueName": "max",
   "targets": [
    {
     "measurement": "solar",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Peak Consumption",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "watt",
   "valueName": "max",
   "targets": [
    {
     "measurement": "home_load",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Home Power Usage",
   "type": "graph",
   "description": "This panel shows the current power being used at home. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "alias": "Home Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "home_load",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "alias": "PV Production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "solar",
     "query": "SELECT mean(\"power\") FROM \"solar\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net Utilization",
   "type": "graph",
   "description": "This panel shows net power consumption. \n\nPositive values are net consumption. \n\nNegative values are net production.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "watt", "label": "Watts" }
   ],
   "targets": [
    {
     "alias": "Net Power Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Amperage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "PV Amperage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "solar",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Home Amperage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "home_load",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}