{
 "title": "FloDashboard Euro",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Range1Hour", "label": "Range1 Start Hour", "query": "${VAR_RANGE1HOUR}" },
   { "name": "Range1Duration", "label": "Range1Duration", "query": "${VAR_RANGE1DURATION}" },
   { "name": "Range2Hour", "label": "Range2 Start Hour", "query": "${VAR_RANGE2HOUR}" },
   { "name": "Range2Duration", "label": "Range2Duration", "query": "${VAR_RANGE2DURATION}" },
   { "name": "Range3Hour", "label": "Range3 Start hour", "query": "${VAR_RANGE3HOUR}" },
   { "name": "Range3Duration", "label": "Range3Duration", "query": "${VAR_RANGE3DURATION}" },
   { "name": "Range4Hour", "label": "Range4 Start Hour", "query": "${VAR_RANGE4HOUR}" },
   { "name": "Range4Duration", "label": "Range4Duration", "query": "${VAR_RANGE4DURATION}" },
   { "name": "Range5Hour", "label": "Range6 Start Hour", "query": "${VAR_RANGE5HOUR}" },
   { "name": "Range5Duration", "label": "Range6Duration", "query": "${VAR_RANGE5DURATION}" },
   { "name": "DayLightSaving", "label": "1h or 2h", "query": "${VAR_DAYLIGHTSAVING}" },
   { "name": "SuperCreuse", "query": "${VAR_SUPERCREUSE}" },
   { "name": "Creuse", "query": "${VAR_CREUSE}" },
   { "name": "Normale", "query": "${VAR_NORMALE}" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "dashlist",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "formule origine",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Salon1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"power\") /3600000 FROM \"raw_cts\" WHERE (\"ct\" = '0') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Salon2",
     "measurement": "raw_cts",
     "query": "SELECT integral(\"power\") /3600000 FROM \"raw_cts\" WHERE (\"ct\" = '5') AND $timeFilter",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ct", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "Chambre",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"power\") /3600000 FROM \"raw_cts\" WHERE (\"ct\" = '1') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Chauffe eau",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"power\") /3600000 FROM \"raw_cts\" WHERE (\"ct\" = '2') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "LaveLinge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"power\") /3600000 FROM \"raw_cts\" WHERE (\"ct\" = '3') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Prise SdB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"power\") /3600000 FROM \"raw_cts\" WHERE (\"ct\" = '4') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Salon1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "SuperCreuse",
     "measurement": "raw_cts",
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $SuperCreuse /10000 FROM \"raw_cts\" WHERE (\"ct\" = '0') AND $timeFilter GROUP BY time($Range1Duration,-$DayLightSaving+$Range1Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range1Hour) GROUP BY time(24h,-$DayLightSaving+$Range1Hour)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ct", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "Creuse1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Creuse/10000 FROM \"raw_cts\" WHERE (\"ct\" = '0') AND $timeFilter GROUP BY time($Range2Duration,-$DayLightSaving+$Range2Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range2Hour) GROUP BY time(24h,-$DayLightSaving+$Range2Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pleine1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Normale /10000 FROM \"raw_cts\" WHERE (\"ct\" = '0') AND $timeFilter GROUP BY time($Range3Duration,-$DayLightSaving+$Range3Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range3Hour) GROUP BY time(24h,-$DayLightSaving+$Range3Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pleine2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Normale /10000 FROM \"raw_cts\" WHERE (\"ct\" = '0') AND $timeFilter GROUP BY time($Range4Duration,-$DayLightSaving+$Range4Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range4Hour) GROUP BY time(24h,-$DayLightSaving+$Range4Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Creuse2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Creuse /10000 FROM \"raw_cts\" WHERE (\"ct\" = '0') AND $timeFilter GROUP BY time($Range5Duration,-$DayLightSaving+$Range5Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range5Hour) GROUP BY time(24h,-$DayLightSaving+$Range5Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Salon2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "SuperCreuse",
     "measurement": "raw_cts",
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $SuperCreuse /10000 FROM \"raw_cts\" WHERE (\"ct\" = '5') AND $timeFilter GROUP BY time($Range1Duration,-$DayLightSaving+$Range1Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range1Hour) GROUP BY time(24h,-$DayLightSaving+$Range1Hour)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ct", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "Creuse1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Creuse/10000 FROM \"raw_cts\" WHERE (\"ct\" = '5') AND $timeFilter GROUP BY time($Range2Duration,-$DayLightSaving+$Range2Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range2Hour) GROUP BY time(24h,-$DayLightSaving+$Range2Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pleine1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Normale /10000 FROM \"raw_cts\" WHERE (\"ct\" = '5') AND $timeFilter GROUP BY time($Range3Duration,-$DayLightSaving+$Range3Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range3Hour) GROUP BY time(24h,-$DayLightSaving+$Range3Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pleine2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Normale /10000 FROM \"raw_cts\" WHERE (\"ct\" = '5') AND $timeFilter GROUP BY time($Range4Duration,-$DayLightSaving+$Range4Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range4Hour) GROUP BY time(24h,-$DayLightSaving+$Range4Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Creuse2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Creuse /10000 FROM \"raw_cts\" WHERE (\"ct\" = '5') AND $timeFilter GROUP BY time($Range5Duration,-$DayLightSaving+$Range5Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range5Hour) GROUP BY time(24h,-$DayLightSaving+$Range5Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chambre",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "SuperCreuse",
     "measurement": "raw_cts",
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $SuperCreuse /10000 FROM \"raw_cts\" WHERE (\"ct\" = '1') AND $timeFilter GROUP BY time($Range1Duration,-$DayLightSaving+$Range1Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range1Hour) GROUP BY time(24h,-$DayLightSaving+$Range1Hour)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ct", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "Creuse1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Creuse/10000 FROM \"raw_cts\" WHERE (\"ct\" = '1') AND $timeFilter GROUP BY time($Range2Duration,-$DayLightSaving+$Range2Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range2Hour) GROUP BY time(24h,-$DayLightSaving+$Range2Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pleine1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Normale /10000 FROM \"raw_cts\" WHERE (\"ct\" = '1') AND $timeFilter GROUP BY time($Range3Duration,-$DayLightSaving+$Range3Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range3Hour) GROUP BY time(24h,-$DayLightSaving+$Range3Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pleine2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Normale /10000 FROM \"raw_cts\" WHERE (\"ct\" = '1') AND $timeFilter GROUP BY time($Range4Duration,-$DayLightSaving+$Range4Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range4Hour) GROUP BY time(24h,-$DayLightSaving+$Range4Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Creuse2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Creuse /10000 FROM \"raw_cts\" WHERE (\"ct\" = '1') AND $timeFilter GROUP BY time($Range5Duration,-$DayLightSaving+$Range5Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range5Hour) GROUP BY time(24h,-$DayLightSaving+$Range5Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overview global",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "RadSalon2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "raw_cts",
     "query": "SELECT integral(\"power\") /3600 FROM \"raw_cts\" WHERE (\"ct\" = '5') AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ct", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "RadSalon1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"power\") /3600 FROM \"raw_cts\" WHERE (\"ct\" = '0') AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Chambre",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"power\") /3600 FROM \"raw_cts\" WHERE (\"ct\" = '1') AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "EauCh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"power\") /3600 FROM \"raw_cts\" WHERE (\"ct\" = '2') AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "LaveLinge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"power\") /3600 FROM \"raw_cts\" WHERE (\"ct\" = '3') AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Prise SDB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT integral(\"power\") /3600 FROM \"raw_cts\" WHERE (\"ct\" = '4') AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chauffe Eau",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "SuperCreuse",
     "measurement": "raw_cts",
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $SuperCreuse /10000 FROM \"raw_cts\" WHERE (\"ct\" = '2') AND $timeFilter GROUP BY time($Range1Duration,-$DayLightSaving+$Range1Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range1Hour) GROUP BY time(24h,-$DayLightSaving+$Range1Hour)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ct", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "Creuse1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Creuse/10000 FROM \"raw_cts\" WHERE (\"ct\" = '2') AND $timeFilter GROUP BY time($Range2Duration,-$DayLightSaving+$Range2Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range2Hour) GROUP BY time(24h,-$DayLightSaving+$Range2Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pleine1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Normale /10000 FROM \"raw_cts\" WHERE (\"ct\" = '2') AND $timeFilter GROUP BY time($Range3Duration,-$DayLightSaving+$Range3Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range3Hour) GROUP BY time(24h,-$DayLightSaving+$Range3Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pleine2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Normale /10000 FROM \"raw_cts\" WHERE (\"ct\" = '2') AND $timeFilter GROUP BY time($Range4Duration,-$DayLightSaving+$Range4Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range4Hour) GROUP BY time(24h,-$DayLightSaving+$Range4Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Creuse2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Creuse /10000 FROM \"raw_cts\" WHERE (\"ct\" = '2') AND $timeFilter GROUP BY time($Range5Duration,-$DayLightSaving+$Range5Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range5Hour) GROUP BY time(24h,-$DayLightSaving+$Range5Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lave Linge",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "SuperCreuse",
     "measurement": "raw_cts",
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $SuperCreuse /10000 FROM \"raw_cts\" WHERE (\"ct\" = '3') AND $timeFilter GROUP BY time($Range1Duration,-$DayLightSaving+$Range1Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range1Hour) GROUP BY time(24h,-$DayLightSaving+$Range1Hour)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ct", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "Creuse1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Creuse/10000 FROM \"raw_cts\" WHERE (\"ct\" = '3') AND $timeFilter GROUP BY time($Range2Duration,-$DayLightSaving+$Range2Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range2Hour) GROUP BY time(24h,-$DayLightSaving+$Range2Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pleine1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Normale /10000 FROM \"raw_cts\" WHERE (\"ct\" = '3') AND $timeFilter GROUP BY time($Range3Duration,-$DayLightSaving+$Range3Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range3Hour) GROUP BY time(24h,-$DayLightSaving+$Range3Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pleine2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Normale /10000 FROM \"raw_cts\" WHERE (\"ct\" = '3') AND $timeFilter GROUP BY time($Range4Duration,-$DayLightSaving+$Range4Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range4Hour) GROUP BY time(24h,-$DayLightSaving+$Range4Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Creuse2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Creuse /10000 FROM \"raw_cts\" WHERE (\"ct\" = '3') AND $timeFilter GROUP BY time($Range5Duration,-$DayLightSaving+$Range5Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range5Hour) GROUP BY time(24h,-$DayLightSaving+$Range5Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Prise SdB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "SuperCreuse",
     "measurement": "raw_cts",
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $SuperCreuse /10000 FROM \"raw_cts\" WHERE (\"ct\" = '4') AND $timeFilter GROUP BY time($Range1Duration,-$DayLightSaving+$Range1Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range1Hour) GROUP BY time(24h,-$DayLightSaving+$Range1Hour)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ct", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "Creuse1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Creuse/10000 FROM \"raw_cts\" WHERE (\"ct\" = '4') AND $timeFilter GROUP BY time($Range2Duration,-$DayLightSaving+$Range2Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range2Hour) GROUP BY time(24h,-$DayLightSaving+$Range2Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pleine1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Normale /10000 FROM \"raw_cts\" WHERE (\"ct\" = '4') AND $timeFilter GROUP BY time($Range3Duration,-$DayLightSaving+$Range3Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range3Hour) GROUP BY time(24h,-$DayLightSaving+$Range3Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pleine2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Normale /10000 FROM \"raw_cts\" WHERE (\"ct\" = '4') AND $timeFilter GROUP BY time($Range4Duration,-$DayLightSaving+$Range4Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range4Hour) GROUP BY time(24h,-$DayLightSaving+$Range4Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Creuse2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $Creuse /10000 FROM \"raw_cts\" WHERE (\"ct\" = '4') AND $timeFilter GROUP BY time($Range5Duration,-$DayLightSaving+$Range5Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range5Hour) GROUP BY time(24h,-$DayLightSaving+$Range5Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}