{
 "title": "FloDashboard Euro Detail",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Range1Hour", "label": "Range1 Start Hour", "query": "${VAR_RANGE1HOUR}" },
   { "name": "Range1Duration", "label": "Range1Duration", "query": "${VAR_RANGE1DURATION}" },
   { "name": "Range2Hour", "label": "Range2 Start Hour", "query": "${VAR_RANGE2HOUR}" },
   { "name": "Range2Duration", "label": "Range2Duration", "query": "${VAR_RANGE2DURATION}" },
   { "name": "Range3Hour", "label": "Range3 Start hour", "query": "${VAR_RANGE3HOUR}" },
   { "name": "Range3Duration", "label": "Range3Duration", "query": "${VAR_RANGE3DURATION}" },
   { "name": "Range4Hour", "label": "Range4 Start Hour", "query": "${VAR_RANGE4HOUR}" },
   { "name": "Range4Duration", "label": "Range4Duration", "query": "${VAR_RANGE4DURATION}" },
   { "name": "Range5Hour", "label": "Range6 Start Hour", "query": "${VAR_RANGE5HOUR}" },
   { "name": "Range5Duration", "label": "Range6Duration", "query": "${VAR_RANGE5DURATION}" },
   { "name": "CTSelection", "label": "Selection of the room" },
   { "name": "DayLightSaving", "label": "Heure Ete ou Hiver", "query": "${VAR_DAYLIGHTSAVING}" },
   { "name": "SuperCreuse", "query": "${VAR_SUPERCREUSE}" },
   { "name": "Creuse", "query": "${VAR_CREUSE}" },
   { "name": "Normale", "query": "${VAR_NORMALE}" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "Num Transfo -- Salon : 0 et 5 / Chambre : 1 / Chauffe Eau : 2 / Lave Linge : 3 / SdBain : 4\r\n\r\nErreur car il prend une valeur fausse au tout debut. Exemple pour le chauffe Eau sur 2jr"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overview global",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Global per hour",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "raw_cts",
     "query": "SELECT integral(\"power\") /3600 FROM \"raw_cts\" WHERE $timeFilter GROUP BY time(30m)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ct", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "type": "dashlist",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Plages",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "SuperCreuse",
     "measurement": "raw_cts",
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\") /3600 FROM \"raw_cts\" WHERE  $timeFilter GROUP BY time($Range1Duration,-$DayLightSaving+$Range1Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range1Hour) GROUP BY time(24h,-$DayLightSaving+$Range1Hour)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ct", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "Creuse1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\") /3600 FROM \"raw_cts\" WHERE  $timeFilter GROUP BY time($Range2Duration,-$DayLightSaving+$Range2Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+ $Range2Hour) GROUP BY time(24h,-$DayLightSaving+$Range2Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pleine1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\") /3600 FROM \"raw_cts\" WHERE $timeFilter GROUP BY time($Range3Duration,-$DayLightSaving+$Range3Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+ $Range3Hour) GROUP BY time(24h,-$DayLightSaving+$Range3Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pleine2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\") /3600 FROM \"raw_cts\" WHERE $timeFilter GROUP BY time($Range4Duration,-$DayLightSaving+$Range4Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range4Hour) GROUP BY time(24h,-$DayLightSaving+$Range4Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Creuse2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\") /3600 FROM \"raw_cts\" WHERE  $timeFilter GROUP BY time($Range5Duration,-1h+$Range5Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range5Hour) GROUP BY time(24h,-$DayLightSaving+$Range5Hour)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 42 }
   ]
  },
  {
   "title": "Total €",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "SuperCreuse",
     "measurement": "raw_cts",
     "query": "select first(\"integral\") from (\nSELECT integral(\"power\")  / 3600000 * $SuperCreuse /10000 FROM \"raw_cts\" WHERE  $timeFilter GROUP BY time($Range1Duration,-$DayLightSaving+$Range1Hour)\n) WHERE time > ('2021-01-01T00:00:00Z' -$DayLightSaving+$Range1Hour) GROUP BY time(24h,-$DayLightSaving+$Range1Hour)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/3600000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ct", "operator": "=", "value": "5" }
     ]
    }
   ]
  }
 ]
}